sudo: required

language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.9
      - g++-5
      - gcc-5
      - cmake

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - mkdir trdrop_c/build
  - mkdir trdrop_lib/build
  - mkdir trdrop_v/build


before_script:
  - cd trdrop_lib/build && cmake .. && make && cd ../..
  - cd trdrop_c/build && cmake .. && cd ../..
  - cd trdrop_v/build && cmake .. && cd ../..

script:
  - cd trdrop_c/build && make && ./trdrop_c; cd ../..
  - cd trdrop_v/build && make && ./trdrop_v

compiler:
  - clang
  - gcc

os:
- linux